baseURL = "https://gongpyung.github.io/"
title = "LENA"
theme = "lena-docs"

pluralizeListTitles = false

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Multilingual configuration
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false

[languages]
  [languages.ko]
    languageName = "한국어"
    weight = 1
    title = "LENA Docs"
    contentDir = "content/ko"
    
  [languages.en]
    languageName = "English"
    weight = 2
    title = "LENA Docs"
    contentDir = "content/en"

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocLogo = "logo.png"
